### ISSUE TITLE
Where is VEGA datasets located?

### ISSUE THREAD

**Issue by dawit1989** [petotamas/APRiL#3]

**Comment by petotamas** [comment]
Please write an e-mail to tamaspeto@passiveradar.eu with your data set preferences or requirements regarding the research you are working on.

**Comment by PowerPress** [comment]
Website is down

**Comment by petotamas** [comment]
After a short maintenance. It is now back online.

**Comment by xyzhao1026** [comment]
I have sent an email to you but have not received a reply

**Comment by petotamas** [comment]
> I have sent an email to you but have not received a reply

Sorry for the delay. Sent you my reply just now.

**Comment by xyzhao1026** [comment]
Hi Mr.&nbsp;Pető Tamás:


Thank you for reading!
I am a first-year graduate student at Fudan University in China.
My research is focused on Signal processing of passive bistatic radar. I have recently studying the code "pyapril" you published on github. The&nbsp; work was so interesting and it was attractive to me.
I am wondering if you could kindly send me the VEGA dataset. I want to reproduce the code you provided, but the laboratory has not provided the data set of passive radar. I promise they will be used only for research purposed.
&nbsp; &nbsp; &nbsp; Thank you very much for your kind consideration and I am looking forward to your early reply.


All the best,
Xinyu Zhao

&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Dec 5, 2023 05:43 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [pyapril/pyapril] Where is VEGA datasets located? (Issue #3)

&nbsp;



  
I have sent an email to you but have not received a reply
  
Sorry for the delay. Sent you my reply just now.

**Comment by petotamas** [comment]
According to the laws of the EU, passive radar technology is regulated by the export control authority and the technology is not allowed to be transferred outside the EU. (VEGA is maintained inside the EU)

https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32021R0821
5A001/g

As a result, I am unable to share measurements data with you without authorization from the export control authority.

Also note that, all the algorithms implemented in pyapril can already be found in the public domain, either directly with code implementation or published in scientific papers / books.
