### ISSUE TITLE
GNU Radio Data Collection

### ISSUE THREAD

**Issue by ss32** [petotamas/APRiL#4]
I am collecting bistatic data with GNU Radio - [raw_capture.grc](https://pastebin.com/Wrgx1FLr),  [sim_capture.grc](https://pastebin.com/6259A6yq).  With the simulated data I see a reasonable correlation map with high correlation at 0 offset and none on the sides

![image](https://github.com/pyapril/pyapril/assets/4565287/c30aee53-75c1-4946-a01e-b86a6b70236c)

However when collecting live data I don't even see the correlation in the middle, never mind any targets.  

![image](https://github.com/pyapril/pyapril/assets/4565287/09af9c0e-0658-4b91-bc08-2d4606c195b3)

My GNU Radio files have a live FFT correlation plot and the source illuminator is very strong, so I would expect to see something at 0 offset.  I am wondering if you have collected data with GNU Radio and if so, are there any considerations that need to be taken in order to record data in a specific format?  Thanks

![image](https://github.com/pyapril/pyapril/assets/4565287/662e2aea-108c-4b86-b469-253035d15a05)
![image](https://github.com/pyapril/pyapril/assets/4565287/5593756d-e358-47d6-bfd6-212ab295478d)

I am feeding chunks of data in 1 second intervals

```python
import numpy as np
import tqdm
from pyapril import detector
from pyapril.RDTools import plot_rd_matrix

C = 3e8 
max_target_velocity = 20 # m/s
carrier_frequency = 91.5e6
fs = 2.048e6  # Sampling frequency [Hz]
dt = 1 # time resolution per frame
chunk_size = int(dt * fs / 2)
lambda_target = C / carrier_frequency
fD_max = 100 #(2 * max_target_velocity) / lambda_target  
print(f'fd_max: {fD_max}')
max_target_range_km = 5  # The simulated sample delay of the target reflection is 12.

print("Loading data...")
x_r_raw = np.fromfile("/tmp/ch1.bin", dtype=complex)
x_s_raw = np.fromfile("/tmp/ch2.bin", dtype=complex)

print(f"Chunk size: {chunk_size}")
print("Data loaded")
dyn_range = 10 * np.log10(chunk_size)  # Dynamic range of the ambiguity function of the noise illuminator signal
r_max = 100 #int(chunk_size / max_target_range_km / 500)
print("r_max :", r_max)
n_chunks = int(len(x_r_raw) / chunk_size)

for i in tqdm.tqdm(range(1,n_chunks),total=n_chunks):
    idx_start = (i-1)*chunk_size
    idx_end = (i*chunk_size)
    # print(f'r_max: {r_max}')
    x_r = x_r_raw[idx_start:idx_end]
    x_s = x_s_raw[idx_start:idx_end]
    rd_matrix = detector.cc_detector_ons(x_r, x_s, fs, fD_max, r_max, verbose=1, Qt_obj=None)
    if rd_matrix is None:
        break
    fig = plot_rd_matrix(rd_matrix,
                    dyn_range=dyn_range,
                    interpolation='best',
                    cmap='jet',
                    scaling_mode="adaptive-floor-fix-range",
                    fs=fs,
                    max_Doppler=fD_max)
    fig.write_image(f"/tmp/frame_{i:02d}",'jpg',scale=3.0)
    ```

**Comment by ss32** [comment]
Closing this as the source of the issue appears to be the gain values I used in GNURadio.  I would still be curious if you @johanna-rock @petotamas have collected data in GNU Radio and processed it using this library.  

![image](https://github.com/pyapril/pyapril/assets/4565287/b4f33b88-a826-41b0-b1d8-1ba82065abb0)
![image](https://github.com/pyapril/pyapril/assets/4565287/910ef2fc-5255-4f62-9915-bfc083362119)

**Comment by petotamas** [comment]
I have not used GNU radio to collect multichannel coherent data for passive radar purposes yet. However if you are working with RTL-SDR receivers you may use this firmware: ( https://github.com/krakenrf/heimdall_daq_fw/tree/main along ) with this small IQ recorder program: ( https://github.com/krakenrf/heimdall_iq_rec/tree/development ) to capture data from multiple receivers. 
The firmware has built-in semi automatic gain control so your gain values will be adjusted to achieve maximum sensitivity but will not be adjusted continuously to maintain phase continuous reception.

**Comment by ss32** [comment]
I will take a look at those, thank you.  Also thank you for making this library open source; it's fantastic.
